kind: Service
apiVersion: v1
metadata:
  name: class-webapp-agent-service 
spec:
  selector:
    app: class-webapp-agent
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  #type: NodePort
