apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-webapp-agent-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: class-webapp-agent
  template:
    metadata:
      labels:
        app: class-webapp-agent
    spec:
      containers:
      - name: class-webapp-agent
        image: habm.koolearn.com/class-webapp-agent/class-webapp-agent
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: harbor-secret
