apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: class-webapp-agent-ingress
spec:
  rules:
  - host: java.wenwiki.com
    http:
      paths:
      - path: /
        backend:
          serviceName: class-webapp-agent-service
          servicePort: 8080
