apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zhishang-webapp-www-ingress
spec:
  rules:
  - host: www.wenwiki.com
    http:
      paths:
      - path: /
        backend:
          serviceName: zhishang-webapp-www-service
          servicePort: 90
